canonical: https://nk23x.github.com/
baseurl: /
excerpt_separator: ""
pygments: true
markdown: kramdown
title: nk23x weblog
tagline: 
description: excursions on github pages
paginate: 3
permalink:   :title

google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal