canonical: https://nk23x.github.com/
baseurl: /
excerpt_separator: ""
pygments: true
markdown: kramdown
title: nk23x:github:pages
tagline: 
description: hello world :)
paginate: 10
paginate_path: "/blog/page:num/"
permalink:   :title
show_downloads: false 
theme: jekyll-theme-minimal
